M48
; DRILL file {KiCad 9.0.2} date 2025-09-27T17:57:00+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-27T17:57:00+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X113.608Y-27.768
X118.608Y-27.768
T2
X217.907Y-143.696
X227.94Y-143.84
T3
X139.281Y-47.6
M30
